# This is a basic workflow to help you get started with Actions

name: Testing-job

# Controls when the workflow will run 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:



# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-1:
    runs-on: self-hosted


    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200
          role-session-name: Test_session
      
      - uses: actions/checkout@v3
        
      - name: Get the Image
        run: | 
          aws s3 ls
     
      - name: set release date
        run: |
          echo "RELEASE_DATE=$(date --rfc-3339=date)" >> ${GITHUB_ENV} 

      - name: Wait for 60
        run: | 
          sleep 60s
          echo ${{env.DATE}}
               
  job-2-Create_Instance:
   ## needs: job-1
    runs-on: self-hosted
    env:
      S3_Bucket: s3-oes-bck-bucke001
      PLATFORM: perf
      

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-duration-seconds: 1200
          role-session-name: Test_session
    
      - name: Get S3 list
        run: |
          aws s3 rb s3://${{env.S3_Bucket}}-${{env.PLATFORM}}
      - name: Copy the file to S3. 
        run: |
          aws s3 cp s3://${{env.S3_Bucket}}-${{env.PLATFORM}}
      - name: Wait for 60
        run: | 
          sleep 60s
      - name: Dummy job
        run: |
          aws ec2 describe-instances --output text
          
          
         
           
          
