# This is a basic workflow to help you get started with Actions

name: Testing-job

# Controls when the workflow will run 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
env: 
  AMI_ID: aws ec2 describe-images --filters 'Name=tag:Name,Values=Test' --query 'sort_by(Images, &CreationDate)[-2].[ImageId]' --output 'text'

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-1:
    AWS-access:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          role-duration-seconds: 1200
          role-session-name: Test_session
      
      - uses: actions/checkout@v3
        
      - name: Get List of s3 buckets
        run: | 
          aws ec2 describe-volumes --output text
     
      - name: Sleep for 30 seconds
        run: |
           sleep 30s
        shell: bash
         
      - name: Test echo and sleep time
        run: |
          echo "Hello World"
          pwd
          ls -lart
          sh test.sh
          echo "${{env.AMI_ID}}""
