# This is a basic workflow to help you get started with Actions

name: Testing-job

# Controls when the workflow will run 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:


# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  job-1:
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.TEST_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.TEST_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1
          role-duration-seconds: 1200
          role-session-name: Test_session
      
      - uses: actions/checkout@v3
        
      - name: Get the Image
        run: | 
          echo "AMI_ID=$(aws ec2 describe-images --region us-east-2 --filters 'Name=tag:Name,Values=Test' --query 'sort_by(Images, &CreationDate)[-1].[ImageId]' --output 'text')" >> $GITHUB_ENV
      - name: Copy image
        run: | 
          echo "${{env.AMI_ID}}"       
          aws ec2 modify-image-attribute --region us-east-2 --image-id "${{env.AMI_ID}}" --launch-permission "Add=[{UserId=276166459503}]"

      - name: Wait for 60
        run: | 
          sleep 60s
      
          
  
  job-2-Create_Instance:
    needs: job-1
    runs-on: self-hosted

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Configure AWS credentials from Test account
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.NEW_AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.NEW_AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
          role-duration-seconds: 1200
          role-session-name: Test_session
      
      - name: Create new ec2
        run: |
          echo "AMI_ID_2=$(aws ec2 describe-images --region us-east-2 --filters 'Name=name,Values=Test' --query 'sort_by(Images, &CreationDate)[-1].[ImageId]' --output 'text')" >> $GITHUB_ENV
          
      - name: Test AMI id
        run: | 
          echo "${{env.AMI_ID_2}}"
          aws ec2 run-instances --image-id "${{env.AMI_ID_2}}" --instance-type t2.micro --key-name Test-Key
         
           
          
